---
title: ""
output: html_notebook
---



Install lsr, psych library if not already installed
```{r}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) # set curretn path as workpath
install.packages('psych')
install.packages('lsr')
```

```{r}
library(lsr)
load( file.path("zeppo.Rdata" )) 
oneSampleTTest( x=grades, mu=67.5 ) #add the mu value here

```
```{r}
install.packages('MKinfer')
```

```{r}
library(MKinfer)
```


```{r}
boot.t.test( x=grades, mu=67.5 )
```






```{r}

load (file.path("harpo.Rdata" ))
str(harpo)
```

```{r}
head( harpo )
```


```{r}
independentSamplesTTest( 
      formula = grade ~ tutor,  # formula specifying outcome and group variables
      data = harpo,             # data frame that contains the variables
      var.equal = TRUE          # assume that the two groups have the same variance
  )
```

```{r}
boot.t.test( 
      formula = grade ~ tutor,  # formula specifying outcome and group variables
      data = harpo            # data frame that contains the variables
  )
```



```{r}
library(car)
```


```{r}
independentSamplesTTest( 
      formula = grade ~ tutor,  # formula specifying outcome and group variables
      data = harpo              # data frame that contains the variables
  )
```
```{r}
leveneTest(grade ~ tutor,  # formula specifying outcome and group variables
      data = harpo)              # data frame that contains the variables)
```


```{r}
load( file.path("chico.Rdata" ))
str(chico) 
```


```{r}
head( chico )
```


```{r}
library( psych )
describe( chico )
```



```{r}
chico$improvement <- chico$grade_test2 - chico$grade_test1 
```


```{r}
head( chico )
```
```{r}
oneSampleTTest( chico$improvement, mu=0 )
```
```{r}
qqnorm( y = chico$improvement )        # draw the QQ plot
```

```{r}
shapiro.test( x = chico$improvement )
```

```{r}
improvement2 <- rchisq(100, 2) 
hist(x = improvement2)
```
```{r}
qqnorm( y = improvement2 ) 
```
```{r}
shapiro.test( x = improvement2 )
```


```{r}
wilcox.test( x = improvement2, mu=0)
```

